language: erlang
otp_release:
  - 19.0
  - 18.3
  - 18.0
matrix:
  include:
      env: >
        TRAVIS_OTP_RELEASE=19.prerelease
        PATH=cache/OTP_19_INSTALL/bin:$PATH
        CPATH=$PWD/cache/OTP_19_INSTALL/lib/erlang/include
        LD_LIBRARY_PATH=$PWD/cache/OTP_19_INSTALL/lib/erlang/lib
addons:
  apt:
    packages:
      - python-sphinx
      - enchant
before_script:
  - psql -c 'CREATE USER zotonic; ALTER USER zotonic CREATEDB;' -U postgres
install: echo "hi" # stub command; otherwise travis runs 'rebar get-deps'
script:
  - make all edocs
  - make test
  - make -C doc/ stubs
  - make -C doc/ SPHINXOPTS='-nW' html
  - ./rebar3 xref
sudo: false
branches:
  only:
    - master
    - 0.x
notifications:
  email:
    # recipients:
    #   - zotonic-commits@googlegroups.com
    on_success: change #[always|never|change] # default: change
    on_failure: always #[always|never|change] # default: always
  irc:
    channels:
      - "chat.freenode.net#zotonic"
    on_success: change #[always|never|change] # default: change
    on_failure: always #[always|never|change] # default: always
    template:
      - "New commit on %{repository_name}/%{branch} by %{author}:  %{message} (%{commit}) "
      - "Build details: %{build_url}"
