language: erlang
matrix:
  include:
    - otp_release: 19.0
      env: BUILD_DOCS=true
    - otp_release: 18.3
    - otp_release: 18.0
    - otp_release: 19.0
      env: ELVIS=true
    - otp_release: 19.0
      env: DIALYZER=true
  allow_failures:
    - otp_release: 19.0
      env: DIALYZER=true
  fast_finish: true

before_script:
  - psql -c 'CREATE USER zotonic; ALTER USER zotonic CREATEDB;' -U postgres
install: echo "hi" # stub command; otherwise travis runs 'rebar get-deps'
script:
  - make all
  - make test
  - if [[ "$BUILD_DOCS" = true ]]; then make edocs; fi
  - if [[ "$BUILD_DOCS" = true ]]; then pip install --user -r doc/requirements.txt; fi
  - if [[ "$BUILD_DOCS" = true ]]; then make -C doc/ stubs; fi
  - if [[ "$BUILD_DOCS" = true ]]; then make -C doc/ SPHINXOPTS='-nW' html; fi
  - ./rebar3 xref
  - if [[ "$ELVIS" = true ]]; then wget https://github.com/inaka/elvis/releases/download/0.2.12/elvis && chmod +x elvis && ./elvis rock; fi
  - if [[ "$DIALYZER" = true ]]; then ./rebar3 dialyzer; fi
sudo: false
branches:
  only:
    - master
    - 0.x
notifications:
  email:
    # recipients:
    #   - zotonic-commits@googlegroups.com
    on_success: change #[always|never|change] # default: change
    on_failure: always #[always|never|change] # default: always
  irc:
    channels:
      - "chat.freenode.net#zotonic"
    on_success: change #[always|never|change] # default: change
    on_failure: always #[always|never|change] # default: always
    template:
      - "New commit on %{repository_name}/%{branch} by %{author}:  %{message} (%{commit}) "
      - "Build details: %{build_url}"
