language: erlang
otp_release:
  - R15B01
  - R14B04
  - R14B03
script: make all edocs
before_install: git submodule update --init --recursive
env:
  - DB=postgres
branches:
  only:
    - master
notifications:
  email:
    recipients:
      - zotonic-commits@googlegroups.com
    on_success: change #[always|never|change] # default: change
    on_failure: always #[always|never|change] # default: always
