language: erlang
otp_release:
  - 18.0
  - 17.4
  - R16B
install: echo "hi" # stub command; otherwise travis runs 'rebar get-deps'
script: make all edocs && make test
sudo: false
branches:
  only:
    - master
    - release-0.13.x
    - release-0.12.x
    - release-0.11.x
notifications:
  email:
    # recipients:
    #   - zotonic-commits@googlegroups.com
    on_success: change #[always|never|change] # default: change
    on_failure: always #[always|never|change] # default: always
  irc:
    channels:
      - "chat.freenode.net#zotonic"
    on_success: change #[always|never|change] # default: change
    on_failure: always #[always|never|change] # default: always
    template:
      - "New commit on %{repository_name}/%{branch} by %{author}:  %{message} (%{commit}) "
      - "Build details: %{build_url}"
